// Generated by https://quicktype.io

class UserModel {
  final String id;
  final String name;
  final String lastName;
  final String email;
  final String password;
  final String createdAt;
  final String updatedAt;

  UserModel(
      {required this.id,
      required this.name,
      required this.lastName,
      required this.email,
      required this.password,
      required this.createdAt,
      required this.updatedAt});

  get() => {
        id: id,
        name: name,
        lastName: lastName,
        email: email,
        password: password,
        createdAt: createdAt,
        updatedAt: updatedAt
      };

  static UserModel fromJson(Map map) => UserModel(
      id: map['id'],
      name: map['name'],
      lastName: map['lastName'],
      email: map['email'],
      password: map['password'],
      createdAt: map['created_at'],
      updatedAt: map['updated_at']);
}
